#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=Scripts/lib/common.sh
source "${SCRIPT_DIR}/common.sh"

usage() {
  cat <<'EOF'
Usage:
  Scripts/lib/patch_info_plist.sh --app "<path-to-app>" [--feed-url "<url>"] [--public-ed-key "<base64>"] [--scheduled-check-interval "<seconds>"]

Patches Sparkle-related keys into an app bundle's Contents/Info.plist.
This is used to keep Sparkle update checks working even when Info.plist is generated by Xcode.
EOF
}

APP_PATH=""
FEED_URL="https://github.com/second-arrow/AerialFlow/releases/latest/download/appcast.xml"
PUBLIC_ED_KEY="yKiWLk0QTYzR6rJNjpM7gmMpd+H44mTPn5rguuGra7I="
SCHEDULED_CHECK_INTERVAL="604800"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --app)
      APP_PATH="${2:-}"; shift 2 ;;
    --feed-url)
      FEED_URL="${2:-}"; shift 2 ;;
    --public-ed-key)
      PUBLIC_ED_KEY="${2:-}"; shift 2 ;;
    --scheduled-check-interval)
      SCHEDULED_CHECK_INTERVAL="${2:-}"; shift 2 ;;
    -h|--help)
      usage; exit 0 ;;
    *)
      die "Unknown arg: $1" ;;
  esac
done

[[ -n "${APP_PATH}" ]] || { usage; die "Missing --app"; }
[[ -d "${APP_PATH}" ]] || die "App not found: ${APP_PATH}"

INFO_PLIST="${APP_PATH}/Contents/Info.plist"
[[ -f "${INFO_PLIST}" ]] || die "Info.plist not found: ${INFO_PLIST}"

PLISTBUDDY="/usr/libexec/PlistBuddy"
[[ -x "${PLISTBUDDY}" ]] || die "PlistBuddy not found: ${PLISTBUDDY}"

set_or_add_string() {
  local key="$1"
  local value="$2"
  if "${PLISTBUDDY}" -c "Print :${key}" "${INFO_PLIST}" >/dev/null 2>&1; then
    "${PLISTBUDDY}" -c "Set :${key} ${value}" "${INFO_PLIST}"
  else
    "${PLISTBUDDY}" -c "Add :${key} string ${value}" "${INFO_PLIST}"
  fi
}

set_or_add_integer() {
  local key="$1"
  local value="$2"
  if "${PLISTBUDDY}" -c "Print :${key}" "${INFO_PLIST}" >/dev/null 2>&1; then
    "${PLISTBUDDY}" -c "Set :${key} ${value}" "${INFO_PLIST}"
  else
    "${PLISTBUDDY}" -c "Add :${key} integer ${value}" "${INFO_PLIST}"
  fi
}

log "Patching Sparkle keys into Info.plist: ${INFO_PLIST}"
set_or_add_string "SUFeedURL" "${FEED_URL}"
set_or_add_string "SUPublicEDKey" "${PUBLIC_ED_KEY}"
set_or_add_integer "SUScheduledCheckInterval" "${SCHEDULED_CHECK_INTERVAL}"

log "Patched:"
log "  SUFeedURL=${FEED_URL}"
log "  SUPublicEDKey=${PUBLIC_ED_KEY}"
log "  SUScheduledCheckInterval=${SCHEDULED_CHECK_INTERVAL}"

